version: '3.7'

services:
  PostgreSQL:
    container_name: PostgreSQL
    image: postgres:12-alpine
    volumes:
      # Initialize the database with the role and database in the init.sh file
      - ./sql/docker/init.sh:/docker-entrypoint-initdb.d/1.sh
      # Uncomment the next line if you need an UUID extension in your database
      # - ./sql/docker/uuidextension.sh:/docker-entrypoint-initdb.d/2.sh
      - ./docker-volumes/postgresql:/var/lib/postgresql
    ports:
      - '5432:5432'
    networks:
      - template

  Template:
    container_name: template
    build:
      context: ./
      dockerfile: dev.Dockerfile
      target: develop
      cache_from:
        - node:12-buster-slim
        - template:1-dev
    image: template:1-dev
    restart: on-failure
    volumes:
      - ./:/template
    env_file:
      - .env
    environment:
      - TYPEORM_HOST=PostgreSQL
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    depends_on:
      - 'PostgreSQL'
    networks:
      - template

networks:
  template:
