version: '3.7'

services:
  postgreSQL:
    container_name: postgreSQL
    image: postgres:12-alpine
    volumes:
      # Initialize the database with the role and database in the init.sh file
      - ./sql/docker/init.sh:/docker-entrypoint-initdb.d/1.sh
      # Uncomment the next line if you need an UUID extension in your database
      # - ./sql/docker/uuidextension.sh:/docker-entrypoint-initdb.d/2.sh
      - postgres_volume:/var/lib/postgresql

  redis:
    container_name: redis
    image: redis:6.0.9-alpine
    volumes:
      - redis_volume:/data

  template-dev:
    <<: &template
      image: template:1-dev
      restart: on-failure
      env_file:
        - .env
      environment:
        - TYPEORM_HOST=postgreSQL
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      ports:
        - "3000:3000"
      depends_on:
        - 'postgreSQL'
        - 'redis'
    container_name: template-dev
    build:
      context: ./
      dockerfile: dev.Dockerfile
      target: develop
      cache_from:
        - node:14.15.1-buster-slim
        - template:1-dev
    volumes:
      - ./:/template

  template-prod:
    <<: *template
    container_name: template-prod
    build:
      context: ./
      dockerfile: Dockerfile
      target: template
      cache_from:
        - node:14.15.1-buster-slim
        - template:1-prod

volumes:
  postgres_volume:
  redis_volume:
