version: '3.3'

services:
  PostgreSQL:
    container_name: PostgreSQL_App
    image: postgres:12-alpine
    ports:
      - '5531:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=app
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql
    networks:
      - vegelibri_app

  App:
    container_name: App
    image: app
    restart: on-failure
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - 'PostgreSQL'
    networks:
      - vegelibri_app

networks:
  vegelibri_app:
    external: true
